apiVersion: v2
name: zitadel
description: A Helm chart for ZITADEL v2
type: application
appVersion: "v2.28.1"
version: 5.0.0
kubeVersion: ">= 1.19.0-0"
icon: https://zitadel.zitadel.cloud/ui/login/resources/themes/zitadel/logo-dark.svg
maintainers:
  - name: zitadel
    email: support@zitadel.com
    url: https://zitadel.com
