apiVersion: v2
name: zitadel
description: A Helm chart for ZITADEL v2
type: application
appVersion: "v2.14.2"
version: 3.6.0
kubeVersion: ">= 1.16.15-0"
icon: https://zitadel.zitadel.cloud/ui/login/resources/themes/zitadel/logo-dark.svg
dependencies:
  - name: cockroachdb
    version: ~8.1.0
    repository: https://charts.cockroachdb.com/
    condition: cockroachdb.enabled
maintainers:
  - name: zitadel
    email: support@zitadel.com
    url: https://zitadel.com
