apiVersion: v2
name: zitadel
description: A Helm chart for ZITADEL
type: application
appVersion: v4.10.1
version: 9.24.0
kubeVersion: '>= 1.30.0-0'
home: https://zitadel.com
sources:
  - https://github.com/zitadel/zitadel
icon: https://zitadel.com/zitadel-logo-dark.svg
keywords:
  - identity
  - oidc
  - oauth
  - auth
  - saml
  - iam
  - sso
  - idp
maintainers:
  - name: zitadel
    email: support@zitadel.com
    url: https://zitadel.com
