apiVersion: v2
name: zitadel
description: A Helm chart for ZITADEL v2
type: application
appVersion: "v2.23.1"
version: 4.6.0
kubeVersion: ">= 1.18.20-0"
icon: https://zitadel.zitadel.cloud/ui/login/resources/themes/zitadel/logo-dark.svg
maintainers:
  - name: zitadel
    email: support@zitadel.com
    url: https://zitadel.com
