apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zitadel.configmapName" . }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
data:
  zitadel-config-yaml: |-
    {{- .Values.zitadel.configmapConfig | toYaml | nindent 4 }}
