{{- if .Values.zitadel.secretConfig -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "zitadel.secretName" . }}
  {{- with .Values.zitadel.secretConfigAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
stringData:
  zitadel-secrets-yaml: |-
    {{ .Values.zitadel.secretConfig | toYaml | nindent 4 }}
{{- end -}}
