{{- if eq .Values.ingress.controller "aws" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zitadel.fullname" . }}-grpc
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/healthcheck-path: /grpc.health.v1.Health/Check
    alb.ingress.kubernetes.io/success-codes: '0'
    {{- if .Values.service }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "zitadel.service.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and .Values.service.externalTrafficPolicy (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "zitadel.containerPort" . }}
      protocol: TCP
      name: {{ regexReplaceAll "\\W+" .Values.service.protocol "-" }}-server
      appProtocol: {{ .Values.service.appProtocol }}
  selector:
    {{- include "zitadel.start.selectorLabels" . | nindent 4 }}
{{- end }}
