{{- if (and .Values.cockroachdb.enabled .Values.cockroachdb.tls.enabled (not .Values.zitadel.secretConfig.Database.User.Password ))}}
{{- fail ".Values.zitadel.secretConfig.Database.User.Password is mandatory for tls enabled cockroach"}}
{{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zitadel-secrets-yaml
stringData:
  zitadel-secrets-yaml: |- 
    {{ .Values.zitadel.secretConfig | toYaml | nindent 4 }}



