name: Typecheck

on:
  push:

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  steep-check:
    runs-on: ubuntu-latest
    name: Inspect Code

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0

      - name: Setup kubeconform
        uses: bmuschko/setup-kubeconform@v1 # v1

      - name: Run make check
        run: make check
