name: Typecheck

on:
  push:

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  steep-check:
    runs-on: ubuntu-latest
    name: Inspect Code

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0

      - name: Setup kubeconform
        uses: bmuschko/setup-kubeconform@v1 # v1

      - name: Run make check
        run: make check
